### ISSUE TITLE
dlopen: cannot load any more object with static TLS

### ISSUE THREAD

**Issue by tiagovas** [i-rinat/freshplayerplugin#225] opened 2015-07-03 18:47 UTC
My freshplayerplugin stopped working. When I open Firefox, the following errors are logged to stdout:

```
LoadPlugin: failed to initialize shared library /usr/lib64/browser-plugins/libfreshwrapper-nacl.so [dlopen: cannot load any more object with static TLS]
LoadPlugin: failed to initialize shared library /usr/lib64/browser-plugins/libfreshwrapper-libpdf.so [dlopen: cannot load any more object with static TLS]
LoadPlugin: failed to initialize shared library /usr/lib64/browser-plugins/libfreshwrapper-pepperflash.so [dlopen: cannot load any more object with static TLS]
```

As a consequence, the plugin doesn't show up in **about:plugins**

Not sure what changed because it was working a few weeks ago.
I'm running freshplayerplugin-0.3.0-3.1.x86_64 on openSUSE 13.2

**Comment by i-rinat** [comment] 2015-07-03 20:56
Hi. Have you tried to build freshwrapper from source?
I've just looked through freshplayerplugin.spec from src.rpm, and it does odd things like dragging GTK+ 3 in. Combining versions 2 and 3 can give unexpected results, so before investigating what happens here, it's worth to try build some kind of reference version.

Also loading `libfreshwrapper-nacl.so` and `libfreshwrapper-libpdf.so` is not a good idea either.

**Comment by tiagovas** [comment] 2015-07-03 21:58
Thanks, Rinat.
I removed libfreshwrapper-nacl.so and libfreshwrapper-libpdf.so from the /usr/lib64/browser-plugins directory. But it's still not working.

I noticed something odd, though: it works when Firefox is run as root!
I have a fair amount of other plugins which work fine when Firefox is run as a normal user. Only libfreshwrapper-pepperflash.so seems not to work. Any idea why?

**Comment by i-rinat** [comment] 2015-07-04 10:19
I don't think removing other libraries would help anyhow. What about building from source, without GTK+ 3?

**Comment by tiagovas** [comment] 2015-07-04 19:27
I've rebuilt freshplayerplugin without GTK+3 but the problem persists.
I've created a new user and logged in as the new user just to check if there wasn't anything fishy in my user environment. Unfortunately, the problem persisted.
It's a mystery why it works when Firefox is run as root...

**Comment by i-rinat** [comment] 2015-07-04 22:27
I didn't remember encountering similar issue ever.
From the error message I can conclude it has something to do with thread-local storage.

Are you using any custom compiler flags during compilation?
Could you also try to compile with the following flags?
```
$ CFLAGS="-ftls-model=global-dynamic" cmake -DCMAKE_BUILD_TYPE=Debug ..
$ make
```

**Comment by i-rinat** [comment] 2015-08-01 18:52
Hello?

**Comment by tiagovas** [comment] 2015-08-02 17:18
Hi Rinat

After installing some updates from openSuSE, the problem "magically" went away and I can use the freshplayer plugin while running as a normal user.

Today, I've updated to freshplayerplugin-0.3.1-9.1.x86_64. Let's how it works...

Thanks

**Comment by i-rinat** [comment] 2015-08-02 19:06
Issue solved by itself, which is good, because I had no idea what to do. :smile:
But I still wonder what caused it.

By any chance, maybe you still have src.rpm of version 0.3.0-3.1.x86_64? It would be good to know how to solve similar issues in the future.

**Comment by frispete** [comment] 2016-05-21 10:35
Dear Rinat,

I'm still struggling with this issue. Here's a description and what I discovered:
In the course of installing a fresh openSUSE 42.1 on two systems, I added freshplayerplugin (of course), while migrating Firefox settings from previous installations to the new environment.
First system was with Firefox 45.something. The dreaded:
```
LoadPlugin: failed to initialize shared library /usr/lib64/browser-plugins/libfreshwrapper-flashplayer.so [dlopen: cannot load any more object with static TLS]
```
appeared, resulting in listing /usr/lib64/browser-plugins/libfreshwrapper-flashplayer.so in the [INVALID] section of pluginreg.dat. After creating a new firefox profile, the error disappeared, and I was able to migrate the most important firefox settings.

Second system, yesterday evening: again, the error appeared, this time, it's Firefox 46.0. 
Again, I created a fresh profile, but this time, the issue persisted, no matter, what I tried.
 * build with -ftls-model={global-dynamic,local-dynamic,initial-exec,local-exec}, -fpic and -fPIC
 * in debug mode
 * deinstalled all other plugins
 * change the order of plugins in pluginreg.dat

The only model, that I wasn't able to compile (ahem, link) is -ftls-model=local-exec:
```
[   24s] /usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/freshwrapper-obj.dir/trace_core.c.o: relocation R_X86_64_TPOFF32 against `tictoc_ts' can not be used when making a shared object; recompile with -fPIC
[   24s] CMakeFiles/freshwrapper-obj.dir/trace_core.c.o: error adding symbols: Bad value
[   24s] collect2: error: ld returned 1 exit status
```
Interesting, trace_core.c is compiled with -fPIC of course. Maybe, this is a hint, where the dynamic modes of thread local storage allocation models (of ld.so) fail, and the error is a red herring.

According to a massive search on the web for that issue, here is the most concise answer:
https://www.cygwin.com/ml/libc-help/2013-11/msg00033.html

For obvious reasons, I didn't try option 1 - rebuilding glibc.
For option 2 and 3, I need your help. I think, that 2 is not an option, hence leaving 3. 
Do you see a possibility to link against a good part of the libs, that freshplayerplugin relies on?

Sorry for the long winded comment, but before giving up, I hope that sharing the findings will help to get on the bottom of this..

**Comment by frispete** [comment] 2016-05-21 11:33
Update: completely removing tictoc_ts from the picture doesn't change the situation..
I forgot to note: I tried both gtk2 and gtk3 builds. The basic build of this package is done here:
https://build.opensuse.org/package/show/home:frispete:branches:multimedia:apps/freshplayerplugin

**Comment by frispete** [comment] 2016-05-21 11:44
To make this complete, here's the documentation of the mess^b^b^b^bTLS:
https://gcc.gnu.org/onlinedocs/gcc/Code-Gen-Options.html
https://gcc.gnu.org/onlinedocs/gcc/Thread-Local.html#Thread-Local
https://www.akkadia.org/drepper/tls.pdf

**Comment by i-rinat** [comment] 2016-05-21 16:13
I'm not familiar with low-level stuff, so this bug is a mystery for me too. I'm going to install x86-64 version openSUSE 42.1 Leap to try to reproduce the issue.

> I think, that 2 is not an option, hence leaving 3. 

As far as I understand, it's the "Rebuild your application so it doesn't dlopen those libraries and instead
links against them"? If yes, that means not only explicitly linking freshwrapper with libpepflashplayer.so, but linking `plugin-container` from Firefox with freshwrapper too. In theory, it's possible without actually rebuilding, by editing those ELF files. That may help or not, but it will prevent other plugins from being loaded by Firefox. Also main Firefox process also tries to load plugins, so it needs to be modified too.

**Comment by i-rinat** [comment] 2016-05-21 16:25
> I tried both gtk2 and gtk3 builds

There is worth note about GTK+ 3 build. Even GTK+ 3 version of Firefox uses a trick that makes plugin container process load GTK+ 2. That trick is required to load NPAPI Flash, as it assumes GTK+ 2 is used. It became a de facto standard for NPAPI plugins.

So mixing unmodified Firefox with GTK+ 3 build of freshplayerplugin will make both GTK+ 2 and 3 loaded in the same process. It could work, it could fail.

**Comment by i-rinat** [comment] 2016-05-21 17:45
> try to reproduce the issue

Nah... It works, again.

@frispete, did you try to build it on a local machine? I just installed OS, then git, compiler, and build dependencies. Then built it, made a symlink to ~/.mozilla/plugins, installed Chrome (to get PepperFlash), and tried some pages with Flash. It works in my virtual machine.

Are you using some more plugins or there are only freshplayerplugin?

**Comment by frispete** [comment] 2016-05-21 18:33
@i-rinat, first of all, thank you very much for your time, much appreciated.

> So mixing unmodified Firefox with GTK+ 3 build of freshplayerplugin will make both GTK+ 2 and 3 loaded in the same process. It could work, it could fail.

Sure, hence gtk2 build is the default

> @frispete, did you try to build it on a local machine? I just installed OS, then git, compiler, and build dependencies. Then built it, made a symlink to ~/.mozilla/plugins, installed Chrome (to get PepperFlash), and tried some pages with Flash. It works in my virtual machine.

Hmm. bad news (from my POV). Could you do me a favour and check the plugin, I built:
```
zypper ar http://download.opensuse.org/repositories/home:/frispete:/branches:/multimedia:/apps/openSUSE_Leap_42.1/home:frispete:branches:multimedia:apps.repo
zypper in freshplayerplugin
```
My aim is to generate packages, that work out of the box without any user intervention, so no ~/,config/freshwrapper.conf, no edits to /etc/freshwapper.conf, etc.., but I tested that as well..

So, my work flow is:
`root$ rpm -Uhv --force .../freshplayerplugin...rpm`
```
user> rm .mozilla/firefox/*.default/pluginreg.dat
user> firefox
```
This issue appeared two times with a default 42.1 desktop deployment: kde, etc..
This setup comes with a couple of preinstalled plug-ins: 
* OpenH264 Video Codec, that comes with Firefox
* PackageKit
* IcedTea Web Plugin
* Skype Buttons for Kopete
but I also tried with all but the H264 codec removed.

The nice thing about openSUSE Build Service, it produces reproducible results.
I do local builds on a different system, as I don't want anything build related on those desktops. Even local builds are set up in a chroot or even kvm environment with just the necessary dependencies installed, which is important for reproducibility. Mind doing something like this as well? 

I will try to reproduce this in a VM as well.
Have you ticked the: add additional repositories during installation to get the current packages?
What kind of virtualization do you use?

**Comment by i-rinat** [comment] 2016-05-21 19:46
> and check the plugin, I built:

Yeah, now I see the error you were talking about, "dlopen: cannot load any more object with static TLS".

By the way, I've seen libconfig9 installed as dependency. It's not required anymore, code doesn't use it.

**Comment by i-rinat** [comment] 2016-05-21 20:06
> What kind of virtualization do you use?

virt-manager, it uses qemu-kvm as a backend.

**Comment by i-rinat** [comment] 2016-05-21 20:38
I guess, issue could be related to the exact configuration of a build machine. Maybe it's a specific compiler or binutils version that triggers the bug. It's hard to debug something I even can't reproduce.

**Comment by frispete** [comment] 2016-05-21 20:47
> Yeah, now I see the error you were talking about, "dlopen: cannot load any more object with static TLS".

That's great. The question is, what's wrong with the build, and other similar ones.
Here's a receipt to build that package locally. Be aware, that it will create a chroot environment in /tmp or /var/tmp:

```
zypper in osc
echo -e "youruserid ALL = NOPASSWD: /usr/bin/build\n" > /etc/sudoers.d/local-build
md ~/src/
cd ~/src
osc co home:frispete:branches:multimedia:apps freshplayerplugin
cd home\:frispete\:branches\:multimedia\:apps/freshplayerplugin
osc build -j8 --no-verify openSUSE_Leap_42.1 x86_64 freshplayerplugin.spec
```
Hopefully complete. The checkout might require a build service account, Dunno.
This will produce something like:
`/var/tmp/build-root/openSUSE_Leap_42.1-x86_64/home/abuild/rpmbuild/RPMS/x86_64/freshplayerplugin-0.3.5-0.x86_64.rpm`
that can be installed with rpm -Uhv --force, and all is set.

> By the way, I've seen libconfig9 installed as dependency. It's not required anymore, code doesn't use it.

This is due to the dependency chain, we don't depend directly on it.
All direct build dependencies are listed in the spec in BuildRequires: lines.

I'm offline for sleeping now, will be back tomorrow.

**Comment by frispete** [comment] 2016-05-21 20:57
> I guess, issue could be related to the exact configuration of a build machine. Maybe it's a specific compiler or binutils version that triggers the bug. It's hard to debug something I even can't reproduce.

Hmm, thought, you was able to reproduce the problem? You cannot?

As written before, this build system makes sure, that this is reproducible. Therefore a couple of freshplayerplugins from different sources all produce the very same result for 42.1.
I branched my package from:
https://build.opensuse.org/package/show/multimedia:apps/freshplayerplugin
but a similar package is available from PackMan:
http://packman.links2linux.org/package/freshplayerplugin

Even uglier as a problem: the very same package works sometimes with the very same Firefox.
Some strange kind of Heisenbug.

**Comment by frispete** [comment] 2016-05-21 21:26
FYI: I'm rebuilding a patched glibc ATM:
https://build.opensuse.org/package/live_build_log/home:frispete:branches:multimedia:apps/glibc/openSUSE_Leap_42.1/x86_64
It will provide another data point. Do you have an idea, which libs are exhausting the static TLS?

**Comment by i-rinat** [comment] 2016-05-21 21:29
Is there a way to make it without registering at that service?

**Comment by frispete** [comment] 2016-05-21 22:28
As I found out right now, no, I'm afraid. 
As it is able to create other distro including debian packages as well, may be it is useful for you, too.
The patched glibc cut it, btw, but I hate the idea of supporting a glibc build of my own:
https://build.opensuse.org/package/view_file/home:frispete:branches:multimedia:apps/glibc/raise-static-TLS-storage.patch?expand=1

**Comment by i-rinat** [comment] 2016-05-21 22:58
I noticed that despite the fact you are building with a native GLESv2 support, your version is not linked to libGLESv2.so.2. I tried to build the same configuration, edit binary, so it's not linked to libGLESv2.so.2. And I think, I started to get the same error. Adding libGLESv2.so.2 line to your version of the binary didn't work. I see no clear way of actually adding another library. Replacing existing entry, which I tested, makes that other entry disappear, so it's a dead end.

So there are two questions: (1) why is your version not linked to libGLESv2.so.2 (and also libssl.so.1.0.0 is missing), and (2) why are you stripping out ANGLE and using native GLES2? Any reasons?

I switched to ANGLE by default because GLES2 support is buggy when one tries to create context via GLX. It also doesn't work for proprietary nVidia drivers. Perhaps, getting context via EGL would work there, but it's buggy on Intel drivers, that's why I switched back to GLX. At the end of the day, using shader translator is the best solution available, if one want to get something working.

**Comment by frispete** [comment] 2016-05-24 13:45
Hi Rinat,

> So there are two questions: (1) why is your version not linked to libGLESv2.so.2 (and also libssl.so.1.0.0 is missing), and (2) why are you stripping out ANGLE and using native GLES2? Any reasons?

1) because the package that I based my build upon, did it that way. (lame answer from my side, I know)
2) See 1): IIRC, there are some license conflicts involved in ANGLE (is that still an issue from your POV?)

The package works fine with a patched glibc btw. 
Will try to resolve your comments, and come back.

I think, that as long as we/me don't locate the source of the problem, it will stay. 
Will check, if there's something hidden in the pepper fresh build, that spoils things up here? 

Thanks, Pete

**Comment by i-rinat** [comment] 2016-05-24 14:30
> because the package that I based my build upon, did it that way. (lame answer from my side, I know)

Well, that implied fixing the build :-). I think there could be -lGLESv2 parameter missing in appropriate pkg-config data file. As far as I know, you have access to the build logs. Could you check if `-lGLESv2` was mentioned there?

> IIRC, there are some license conflicts involved in ANGLE (is that still an issue from your POV?)

Honestly, I have no idea about any license conflicts. I always were carefully avoiding anything GPL or LGPL-licensed, and also distributing proprietary stuff like PepperFlash binary itself.

If you know any information about why ANGLE couldn't be used, please tell me. As far as I know, it's sufficient to include `/3rdparty/angle/LICENSE` file in the binary distribution for strict license compliance.

**Comment by i-rinat** [comment] 2016-06-11 21:02
I believe issue can be solved either by explicit linking with libGLESv2.so or by building a version that uses ANGLE.

I'm closing issue now. Feel free to reopen or create another, if necessary.

**Closed by i-rinat** 2016-06-11 21:02 UTC
