### ISSUE TITLE
new segfault issue in 0.2.4

### ISSUE THREAD

**Issue by Zombie-Ryushu** [i-rinat/freshplayerplugin#192] opened 2015-06-01 18:11 UTC
I still get the segfault issue 4499831.642708] Chrome_ChildThr[29459]: segfault at 0 ip 00007f7904d7201c sp 00007f78fd1fd610 error 6 in libmozalloc.so[7f7904d71000+2000] occasionally when Flash is triggered. This can crash FireFox.

**Comment by i-rinat** [comment] 2015-06-01 18:24
Hi. Have you tried to build plugin from `master` branch?

**Comment by Zombie-Ryushu** [comment] 2015-06-01 18:40
Yes. Thats where our builds come from for Rosa.

**Comment by i-rinat** [comment] 2015-06-02 19:22
Does this happen often?
Is there any specific scenario which leads to crashes?
Does `plugin-container` process crash or it's a `firefox`? (I've never seen crashing browser process, only plugin container. Latter runs in a separate process).

**Comment by Zombie-Ryushu** [comment] 2015-06-02 19:34
This doesn't appear to be plugin-container. 0.2.3 used to do it constantly. this crash is different. Normally it happens on Youtube using the HTML5 Player, as Youtube causes Flash to trigger xrandr every time its detected.

**Comment by i-rinat** [comment] 2015-06-02 20:57
> as Youtube causes Flash to trigger xrandr every time its detected.

I don't think I get it. Could you explain it in more detail?
I've tried to switch to HTML5 player on Youtube. From that point there were no Flash instances on the page, which means no code from freshwrapper was executed at all. Does it have an effect nonetheless?

**Comment by Zombie-Ryushu** [comment] 2015-06-02 21:07
Yes. I have one system whose monitor does  not send back correct EIED information about screen resolutions supported. Because of this issue with this monitor, under the nvidia 304.125 drivers, the monitor resets every time xrandr is executed from the command line or otherwise. Every time that Youtube loads, HTML5 or no, the Flash plugin is initialized to detect its presence. FreshPlayerPlugin triggers an xrandr call causing the screen to "wink". 

But thats just how I know FreshPlayer Plugin is being initialized and immediately exited because HTML5 is being used. This initialization happens every time that a new Youtube Video is played, and after a certain number of Videos played, FireFox exits with a Segfault.

**Comment by i-rinat** [comment] 2015-06-02 22:55
Try with debug version of Firefox.
I use following `.mozconfig` file:
```
ac_add_options --disable-jemalloc
ac_add_options --enable-valgrind
ac_add_options --enable-optimize="-g -O"
```
You download Firefox sources, create `.mozconfig` file at source root, then run `./mach build`. Compiled binaries would be at `./obj-x86_64-unknown-linux-gnu/dist/bin/`
Config above disables jemalloc and makes memory allocation more Valgrind-friendly. It's unlikely you'll be able to use browser running under Valgrind, but at least backtraces would be much better.

I'm still not sure how can freshwrapper affect main browser process. Again, that's odd.

**Comment by i-rinat** [comment] 2015-08-02 20:46
Hi. Have you any chance to run it under Valgrind?

**Comment by Zombie-Ryushu** [comment] 2015-08-03 00:06
No, I have not. I've been sick for the past few days.  But the issue may not be freshplayerplugin's after all. I loaded different Video drivers on that system, It's doesn't reset the resolution with an improper EDID response. I'm now chasing a much bigger stability issue in FireFox and Thunderbird.

**Comment by i-rinat** [comment] 2015-08-09 19:24
Unfortunately I can't do anything about the bug without additional information.
I'm closing this since you don't have it reproducing anymore.

If you'll get more information, feel free to reopen.

**Closed by i-rinat** 2015-08-09 19:24 UTC
