### ISSUE TITLE
Release 0.3 crashes Atril doc. viewer

### ISSUE THREAD

**Issue by SerGIlles** [i-rinat/freshplayerplugin#213] opened 2015-06-23 01:42 UTC
I installed 0.3 from AUR and when I start Atril I get as follows.
Removing freshplayerplugin resolves the issue.

atril

(atril:7084): Gtk-WARNING **: Theme directory 48x48/status of theme Just Another buuf Remix 5.7.1.3 has no size field

No bp log location saved, using default.
[000:000] Cpu: 6.23.6, x4, 3000Mhz, 3954MB
[000:000] Computer model: Not available
[000:000] Browser XEmbed support present: 1
[000:000] Browser toolkit is Gtk2.
[000:000] Using Gtk2 toolkit
libva info: VA-API version 0.37.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/dri/nvidia_drv_video.so
libva info: Found init function __vaDriverInit_0_35
libva info: va_openDriver() returns 0
NOT SANDBOXED
[000:147] Warning(optionsfile.cc:30): Load: Could not open file, err=2
[000:147] No bp log location saved, using default.
[000:148] Cpu: 6.23.6, x4, 3000Mhz, 3954MB
[000:148] Computer model: Not available
[000:148] Browser XEmbed support present: 1
[000:148] Browser toolkit is Gtk2.
[000:148] Using Gtk2 toolkit
No bp log location saved, using default.
[000:000] Cpu: 6.23.6, x4, 3000Mhz, 3954MB
[000:000] Computer model: Not available
[000:000] Warning(optionsfile.cc:30): Load: Could not open file, err=2
[000:000] No bp log location saved, using default.
[000:001] Cpu: 6.23.6, x4, 3000Mhz, 3954MB
[000:001] Computer model: Not available
[000:151] Warning(optionsfile.cc:30): Load: Could not open file, err=2
[000:151] No bp log location saved, using default.
[000:152] Cpu: 6.23.6, x4, 3000Mhz, 3954MB
[000:152] Computer model: Not available
[000:152] Browser XEmbed support present: 1
[000:152] Browser toolkit is Gtk2.
[000:152] Using Gtk2 toolkit
[000:002] Warning(optionsfile.cc:30): Load: Could not open file, err=2
[000:002] No bp log location saved, using default.
[000:002] Cpu: 6.23.6, x4, 3000Mhz, 3954MB
[000:002] Computer model: Not available
libva info: VA-API version 0.37.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/dri/nvidia_drv_video.so
libva info: Found init function __vaDriverInit_0_35
libva info: va_openDriver() returns 0
java version "1.7.0_79"
OpenJDK Runtime Environment (IcedTea 2.5.5) (Arch Linux build 7.u79_2.5.5-1-x86_64)
OpenJDK 64-Bit Server VM (build 24.79-b02, mixed mode)
[ERROR:flash/platform/pepper/common/pep_process.cpp(19)] CHECK(g_process_type == PROCESS_TYPE_UNKNOWN) failed
Aborted (core dumped)

**Comment by i-rinat** [comment] 2015-06-23 07:50
Hi. Have you tried newest version from `master` branch?  I believe the issue is fixed by 7243809dcbe8b2dac9695ee095367cc1ac2b40d4.

**Comment by SerGIlles** [comment] 2015-06-24 07:33
master branch indeed solves this problem, but it stills gives me problems with some webpages with pure java/html (no flash) video elements, like http://www.b92.net/video/

**Comment by i-rinat** [comment] 2015-06-24 10:25
Could you clarify a bit what "problems" mean? Does it crash, or hang, or something?

**Comment by SerGIlles** [comment] 2015-06-25 00:48
I can't play a video. Usually, I can play one, then with the next one clicking on play button produces nothing. Even restarting FF doesn't help. Uninstalling freshplayerplugin, however, does and everything is back to normal.

**Comment by i-rinat** [comment] 2015-06-25 09:03
Do you have hardware decoding enabled (`enable_hwdec=1` setting in freshwrapper.conf file) ?

**Comment by SerGIlles** [comment] 2015-06-26 02:03
Same thing either way (enable_hwdec=0/1) 
I did not touch:
enable_vdpau = 1
enable_vaapi = 1

**Comment by i-rinat** [comment] 2015-08-01 19:41
> but it stills gives me problems with some webpages with pure java/html (no flash) video elements

Hi. I was reviewing open issues, and have read that message again. Probably I was misreading it then, but now it doesn't make sense: no flash means no single bit of freshplayerplugin is called, so it shouldn't interact anyhow.

I don't remember how it was then, but now b92.net uses Flash for videos, but all controls are indeed are made of HTML+Javascript. So I press play, see gray rectangle (I use ask-to-activate), activate plugins for the site, and it plays fine. So do other videos.

Are there any messages if you start browser from terminal, and try to play videos from that site?

**Comment by SerGIlles** [comment] 2015-08-11 02:14
Hi,
I do not have any flash now installed in FF in either Linux or Windows and B92 works fine. Therefore, it plays in HTML5 just fine. It probably uses flash if available and the problem arises then with this plugin. I haven't encounter this problem in either Chrome on Linux or any browser in Windows (with or without flash installed).

**Comment by i-rinat** [comment] 2015-11-06 16:54
Closing this since original issue was resolved.

If you are still having issues with Flash and b92, please create a new issue with instructions about how to reproduce bug you have (usual three parts, what do you do, what happens, and what should happen). I've tried several cases, but they all work on my machine, so I can't find where issue is without external help.

**Closed by i-rinat** 2015-11-06 16:54 UTC
