### ISSUE TITLE
freshplayerplugin suddenly consume overr 100% cpu and hang

### ISSUE THREAD

**Issue by redhatlinux10** [i-rinat/freshplayerplugin#105] opened 2014-12-13 08:24 UTC
os:openSUSE 13.2
firefox: 14.0.5
chrome-beta: 40.0.2214.38 beta (64-bit)
freshplayerplugin:2.0-32.1

i have already edit file /etc/freshwrapper.conf and edit pepperflash_path's value to '/opt/google/chrome-beta/PepperFlash/libpepflashplayer.so' to make sure freshplayerplugin is using the same ppapi flash as chrome-beta

test link: http://v.youku.com/v_show/id_XODQ3NjM0MjA0.html
when the flash video begins to play, i run pidstat command to watch plugin-container's cpu usage. at first  this process uses about 50% cpu and the video plays as expected. but after about one minute, i find the flash's video hangs and cpu usage is over 100%.
then i open the same link and play with chrome-beta. everything is ok.

**Comment by redhatlinux10** [comment] 2015-01-31 02:20
@MALLER-LAGOON what system configuration do you think it is ? i have changed freshplayerplugin repo from https://build.opensuse.org/package/show?project=home%3Aandykimpe%3Afreshplayerplugin&package=freshplayerplugin to https://build.opensuse.org/package/show?project=home%3AKenzy%3Apackages&package=freshplayerplugin, but this doesn't help. i also have tried to enable/disable gpu acceleration on video context menu but still doesn't help. or how can i debug this wrapper ? any logs for me to deep into ?

**Comment by MALLER-LAGOON** [comment] 2015-01-31 03:48
but buddy, have u tried to compile the freshplayer from this github?
the repos that u linked me are very outdated.

also you can try with [this application](https://github.com/MALLER-LAGOON/Freshplayer-installer), which download the source code from the master branch of this github, compile it and install it properly to the user from the console.

its very important that u read and follow the instructions to this works properly.

i do it in that way, and i can ensure you, the freshplayer works a lot more stable than a flashplayerplugin-nonfree from the oficial repo of Debian.

**Comment by redhatlinux10** [comment] 2015-02-04 12:39
@MALLER-LAGOON  as you requested, [freshplayerplugin from home:Kenzy:packages](https://build.opensuse.org/package/show?project=home%3AKenzy%3Apackages&package=freshplayerplugin) updated freshplayerplugin source codes to commit c5694f0 which is commited on Feb 2, 2015. but still the same problem exists. i have tried to tune some parameters (such as enable_3d, comment flash_command_line) but didn't help.

![updated-freshplayerplugin](https://cloud.githubusercontent.com/assets/1210201/6040519/dcffcf54-acad-11e4-8d67-2b832e48214e.png)

**Comment by i-rinat** [comment] 2015-02-04 22:56
I still can't reproduce the issue you described. Although there were memory leaks, which are now fixed.

Can you build a debug build (`cmake -DCMAKE_BUILD_TYPE=Debug .. && make`) and run a `sudo perf top` when those high CPU load occur?

(`perf` is a profiler, and usually a part of linux-tools package. `perf top` outputs a live list of most CPU expensive functions. It's like `top`, but more specific. Most probably you'll need to run perf as root.)

**Comment by redhatlinux10** [comment] 2015-02-07 00:36
right now i cloned freshplayerplugin ( commit 9a3e1f0) and build a debug build on my own machine which can reproduce this issue , but still any videos on http://www.youku.com will hang after about 1minute. the following is sudo perf top snapshot when video hangs.
![004](https://cloud.githubusercontent.com/assets/1210201/6089844/30e09e26-aea4-11e4-8513-fed080b85e2f.png)

**Comment by MALLER-LAGOON** [comment] 2015-02-07 02:32
did u try setting the storage to unlimited?

**Comment by redhatlinux10** [comment] 2015-02-07 13:09
@MALLER-LAGOON i can not find any similar configurations with local storage. would you please tell me which one it is ?

**Comment by MALLER-LAGOON** [comment] 2015-02-07 15:57
do a right click on the flash frame-->settings-->local storage.

![local-storage](https://cloud.githubusercontent.com/assets/7074901/6092708/ecf4657e-aec8-11e4-9f83-e5dcc6165406.png)

**Comment by redhatlinux10** [comment] 2015-02-07 16:42
@MALLER-LAGOON also tried and same problem

**Comment by redhatlinux10** [comment] 2015-02-08 03:04
this is my debug informations
```
WARNING: content window passed to PrivateBrowsingUtils.isWindowPrivate. Use isContentWindowPrivate instead (but only for frame scripts).
pbu_isWindowPrivate@resource://gre/modules/PrivateBrowsingUtils.jsm:25:14
injectController@resource://gre/modules/MozSocialAPI.jsm:49:20
exports.Utils.yield@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/bruce/.mozilla/firefox/i7tqmpwq.default-1418924289071/extensions/%7Bd10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d%7D.xpi!/bootstrap.js -> jar:file:///home/bruce/.mozilla/firefox/i7tqmpwq.default-1418924289071/extensions/%7Bd10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d%7D.xpi!/lib/utils.js:380:12
INIParser.prototype.process@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/bruce/.mozilla/firefox/i7tqmpwq.default-1418924289071/extensions/%7Bd10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d%7D.xpi!/bootstrap.js -> jar:file:///home/bruce/.mozilla/firefox/i7tqmpwq.default-1418924289071/extensions/%7Bd10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d%7D.xpi!/lib/filterStorage.js:870:7
exports.IO.readFromFile/onProgress@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/bruce/.mozilla/firefox/i7tqmpwq.default-1418924289071/extensions/%7Bd10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d%7D.xpi!/bootstrap.js -> jar:file:///home/bruce/.mozilla/firefox/i7tqmpwq.default-1418924289071/extensions/%7Bd10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d%7D.xpi!/lib/io.js:97:15
exports.IO.readFromFile/<@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/bruce/.mozilla/firefox/i7tqmpwq.default-1418924289071/extensions/%7Bd10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d%7D.xpi!/bootstrap.js -> jar:file:///home/bruce/.mozilla/firefox/i7tqmpwq.default-1418924289071/extensions/%7Bd10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d%7D.xpi!/lib/io.js:182:11
TaskImpl_run@resource://gre/modules/Task.jsm:330:41
Handler.prototype.process@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:865:23
this.PromiseWalker.walkerLoop@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:744:7
NOT SANDBOXED
[fresh 11017] not implemented: PPB_OpenGLES2DrawBuffers(Dev);1.0
[fresh 11017] [PPB] {fake} ppb_video_capture_enumerate_devices
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh 11017] [PPB] {zilch} ppb_network_monitor_update_network_list
[fresh 11017] [PPB] {zilch} ppb_text_input_interface_set_text_input_type instance=10, type=PP_TEXTINPUT_TYPE_DEV_NONE
[fresh 11017] [PPB] {zilch} ppb_flash_set_instance_always_on_top instance=10, on_top=1
[fresh 11017] [PPB] {fake} ppb_video_capture_close
[fresh 11017] [PPB] {fake} ppb_video_capture_enumerate_devices
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh 11017] [PPB] {zilch} ppb_network_monitor_update_network_list
[fresh 11017] [PPB] {zilch} ppb_text_input_interface_set_text_input_type instance=11, type=PP_TEXTINPUT_TYPE_DEV_NONE
[fresh 11017] [PPB] {zilch} ppb_flash_set_instance_always_on_top instance=11, on_top=1
[fresh 11017] [PPB] {fake} ppb_video_capture_close
[fresh] [warning] handle_tcp_connect_stage2, evdns returned code 3, count = 0 (localhost:843)
[fresh] [warning] ppb_tcp_socket_get_local_address, not connected
[fresh] [warning] ppb_tcp_socket_get_remote_address, not connected
[fresh 11017] [PPB] {fake} ppb_video_capture_enumerate_devices
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh 11017] [PPB] {zilch} ppb_network_monitor_update_network_list
[fresh 11017] [PPB] {zilch} ppb_text_input_interface_set_text_input_type instance=12, type=PP_TEXTINPUT_TYPE_DEV_NONE
[fresh] [warning] handle_tcp_connect_stage2, evdns returned code 3, count = 0 (localhost:8909)
[fresh] [warning] ppb_tcp_socket_get_local_address, not connected
[fresh] [warning] ppb_tcp_socket_get_remote_address, not connected
[fresh 11017] [PPB] {fake} ppb_video_capture_close
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh 11017] [PPB] {zilch} ppb_udp_socket_bind udp_socket=1547, addr=0x7f2e04bfd9b0, callback={.func=0x7f2e06254c00, .user_data=0x7f2e018ce0b0, .flags=0}
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh] [warning] handle_tcp_connect_stage2, evdns returned code 3, count = 0 (localhost:843)
[fresh] [warning] ppb_tcp_socket_get_local_address, not connected
[fresh] [warning] ppb_tcp_socket_get_remote_address, not connected
[fresh] [warning] handle_tcp_connect_stage2, evdns returned code 3, count = 0 (localhost:8909)
[fresh] [warning] ppb_tcp_socket_get_local_address, not connected
[fresh] [warning] ppb_tcp_socket_get_remote_address, not connected
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh] [warning] handle_tcp_connect_stage2, evdns returned code 3, count = 0 (localhost:843)
[fresh] [warning] ppb_tcp_socket_get_local_address, not connected
[fresh] [warning] ppb_tcp_socket_get_remote_address, not connected
[fresh] [warning] handle_tcp_connect_stage2, evdns returned code 3, count = 0 (localhost:8909)
[fresh] [warning] ppb_tcp_socket_get_local_address, not connected
[fresh] [warning] ppb_tcp_socket_get_remote_address, not connected
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh 11017] [PPB] {zilch} ppb_udp_socket_bind udp_socket=4688, addr=0x7f2e04bfd9b0, callback={.func=0x7f2e06254c00, .user_data=0x7f2e018ceec0, .flags=0}
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh] [warning] handle_tcp_connect_stage2, evdns returned code 3, count = 0 (localhost:843)
[fresh] [warning] ppb_tcp_socket_get_local_address, not connected
[fresh] [warning] ppb_tcp_socket_get_remote_address, not connected
[fresh] [warning] handle_tcp_connect_stage2, evdns returned code 3, count = 0 (localhost:8909)
[fresh] [warning] ppb_tcp_socket_get_local_address, not connected
[fresh] [warning] ppb_tcp_socket_get_remote_address, not connected
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh] [warning] handle_tcp_connect_stage2, evdns returned code 3, count = 0 (localhost:843)
[fresh] [warning] ppb_tcp_socket_get_local_address, not connected
[fresh] [warning] ppb_tcp_socket_get_remote_address, not connected
[fresh] [warning] handle_tcp_connect_stage2, evdns returned code 3, count = 0 (localhost:8909)
[fresh] [warning] ppb_tcp_socket_get_local_address, not connected
[fresh] [warning] ppb_tcp_socket_get_remote_address, not connected
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh] [warning] handle_tcp_connect_stage2, evdns returned code 3, count = 0 (localhost:843)
[fresh] [warning] ppb_tcp_socket_get_local_address, not connected
[fresh] [warning] ppb_tcp_socket_get_remote_address, not connected
[fresh] [warning] handle_tcp_connect_stage2, evdns returned code 3, count = 0 (localhost:8909)
[fresh] [warning] ppb_tcp_socket_get_local_address, not connected
[fresh] [warning] ppb_tcp_socket_get_remote_address, not connected
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh] [warning] handle_tcp_connect_stage2, evdns returned code 3, count = 0 (localhost:843)
[fresh] [warning] ppb_tcp_socket_get_local_address, not connected
[fresh] [warning] ppb_tcp_socket_get_remote_address, not connected
[fresh] [warning] handle_tcp_connect_stage2, evdns returned code 3, count = 0 (localhost:8909)
[fresh] [warning] ppb_tcp_socket_get_local_address, not connected
[fresh] [warning] ppb_tcp_socket_get_remote_address, not connected
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
WARNING: content window passed to PrivateBrowsingUtils.isWindowPrivate. Use isContentWindowPrivate instead (but only for frame scripts).
pbu_isWindowPrivate@resource://gre/modules/PrivateBrowsingUtils.jsm:25:14
injectController@resource://gre/modules/MozSocialAPI.jsm:49:20
[fresh 11017] [PPB] {fake} ppb_video_capture_enumerate_devices
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh 11017] [PPB] {zilch} ppb_network_monitor_update_network_list
[fresh 11017] [PPB] {zilch} ppb_text_input_interface_set_text_input_type instance=13, type=PP_TEXTINPUT_TYPE_DEV_NONE
[fresh 11017] [PPB] {fake} ppb_video_capture_close
WARNING: content window passed to PrivateBrowsingUtils.isWindowPrivate. Use isContentWindowPrivate instead (but only for frame scripts).
pbu_isWindowPrivate@resource://gre/modules/PrivateBrowsingUtils.jsm:25:14
injectController@resource://gre/modules/MozSocialAPI.jsm:49:20
[fresh 11017] [PPB] {fake} ppb_video_capture_enumerate_devices
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices
[fresh 11017] [PPB] {zilch} ppb_network_monitor_update_network_list
[fresh 11017] [PPB] {zilch} ppb_text_input_interface_set_text_input_type instance=14, type=PP_TEXTINPUT_TYPE_DEV_NONE
[fresh 11017] [PPB] {fake} ppb_video_capture_close
[fresh 11017] [PPB] {fake} ppb_audio_input_enumerate_devices

```

**Comment by i-rinat** [comment] 2015-02-08 16:45
I'm trying to reproduce the issue in virtual machine with OpenSUSE 13.2 installed, but with no success.

As a wild guess, try to temporarily rename `/usr/lib64/gtk-2.0/2.10.0/engines/liboxygen-gtk.so`. In my experiments it showed some errors when run under Valgrind.

**Comment by i-rinat** [comment] 2015-02-08 16:48
From debug log you attached, I can say your system have troubles resolving `localhost`. Is `ping localhost` works on your machine?
It could be you don't have `127.0.0.1	localhost` line in your `/etc/hosts`. That can cause errors in other network-related applications too.

**Comment by redhatlinux10** [comment] 2015-02-08 17:06
>From debug log you attached, I can say your system have troubles resolving localhost. Is ping localhost works on your machine?
It could be you don't have 127.0.0.1 localhost line in your /etc/hosts. That can cause errors in other network-related applications too.

no, i can ping localhost, i also have `127.0.0.1 localhost` line in my `/etc/hosts`

**Comment by redhatlinux10** [comment] 2015-02-09 11:18
>try to temporarily rename /usr/lib64/gtk-2.0/2.10.0/engines/liboxygen-gtk.so

i tried and didn't fix my problem.

**Comment by redhatlinux10** [comment] 2015-02-09 11:27
i also diabled all plugins except this one, disabled all extensions, cleaned all caches and cookies etc ,still didnt' solve my problem.

**Comment by HybridDog** [comment] 2015-02-13 16:32
maybe this is the right place to write this
When l played the game http://www.kongregate.com/games/KintoGames/bit-dungeon
with the freshplayerplugin and clicked somewhere to walk with the character, the game is freezed a bit and then the charakter is near the place where it should walk.
l switched back to flashplugin-installer and l can watch the character starting to walk.
l don't use hardware accelerating.

**Comment by redhatlinux10** [comment] 2015-04-05 05:31
again i git-pulled and compiled, and found this problem is gone with  52b52e735206ff72f8f8c057b8e83e165da54d76 !

**Comment by HybridDog** [comment] 2015-04-05 08:16
Is it fixed in the ppa, too?

**Comment by i-rinat** [comment] 2015-04-05 15:12
> and found this problem is gone

Good to hear that (because I have no idea how to reproduce it and therefore, to fix). Could you also check the most recent version from `master` branch? I've put there some changes, hope they're not breaking it again.

**Closed** 2015-04-24 22:01 UTC
