### ISSUE TITLE
enable 3d not work  for master branch

### ISSUE THREAD

**Issue by beew** [i-rinat/freshplayerplugin#196] opened 2015-06-04 22:36 UTC
Video  plays back is very slow  and stuttering, after about a minute it freezes and then breaks up into horizontal stripes for all sites tested. Setting enable 3d to 0 then it works again. Tested on Ubuntu 15.04 and Fedora 22 on machines with intel and AMD gpu (open driver) 

This happens only with the Master branch, the Widevine branch (I suppose that is the released branch?)  works with 3d enabled with no problem.

**Comment by i-rinat** [comment] 2015-06-05 07:23
Try to configure with
`cmake -DWITH_HWDEC=0 -DCMAKE_BUILD_TYPE=RelWithDebInfo ..`
i.e. disable hardware video decoding.

> Setting enable 3d to 0 then it works again.

HW decoding depends on 3d.

> the Widevine branch (I suppose that is the released branch?) 

It was experimental branch with Widevine plugin (content decryptor bundled with Chrome) enabled. Not useful actually. The relevant difference is that code in that branch doesn't have hwdec, but still have 3d.

**Comment by beew** [comment] 2015-06-05 08:07
Thanks. I see. Please fix hardware decoding. It was working a few days before.

**Comment by i-rinat** [comment] 2015-06-05 08:26
> It was working a few days before.

A few days before there were no hardware-accelerated decoding.

But you are right, with hwdec framerate is decreasing to about 15 fps, which is perceived a stuttering. Don't know why it decresing yet.

**Comment by beew** [comment] 2015-06-05 08:30
Hi, a few days ago I was installing from webupd8's ppa http://www.webupd8.org/2015/04/fresh-player-plugin-024-released-with.html, there was an update today and it stopped working. I compiled from master and see the same problem, so I thought the ppa must have updated from the latest master.

**Comment by i-rinat** [comment] 2015-06-05 13:17
Patch 9fc4abc869e2778552880bd8b701b2e1c0510003 fixes lags on my machine, although limit of 40fps still remains. I saw similar limit in Chrome too, so that could be something related to internals of PepperFlash. And unlikely "freezes" "horizontal stripes" will be fixed by the patch.

**Comment by i-rinat** [comment] 2015-06-05 16:45
Added config file option in 2bca328c8604f00305e4e3f0b592767693df8e9b, `enable_hwdec`, which is disabled by default. Enable it in configuration file if you still want to have hardware-accelerated decoding.

**Comment by MALLER-LAGOON** [comment] 2015-06-08 04:56
@i-rinat is this message normal?

>NOT SANDBOXED
[fresh  5801] not implemented: PPB_OpenGLES2DrawBuffers(Dev);1.0
[fresh] [warning] ppb_var_var_to_utf8, 'var' is not a string, (0)
[fresh] [warning] ppb_graphics3d_create, some of GLX_ARB_create_context, GLX_ARB_create_context_profile, GLX_EXT_create_context_es2_profile missing

**Comment by i-rinat** [comment] 2015-06-08 10:00
> `[fresh 5801] not implemented: PPB_OpenGLES2DrawBuffers(Dev);1.0`

That's OK, since PepperFlash doesn't have strict requirement for  `PPB_OpenGLES2DrawBuffers(Dev);1.0`. As far as I know, `glDrawBuffers` appeared in OpenGL|ES 3.0.

> `[fresh] [warning] ppb_var_var_to_utf8, 'var' is not a string, (0)`

I saw that too. But since everything still works, didn't try to figure out what it was.

> `[fresh] [warning] ppb_graphics3d_create, some of GLX_ARB_create_context, GLX_ARB_create_context_profile, GLX_EXT_create_context_es2_profile missing`

OpenGL|ES 2 interface won't be available for PepperFlash. It will use CPU exclusively for drawing and scaling.

> `[fresh] [error] ppb_message_loop_get_depth, bad resource`

That's bad. Message loop was terminated while other code still relied on its presence. That may cause plugin (and browser) to freeze. Unfortunately, that error is too vague, so there is no enough information to determine where bug is.

**Comment by i-rinat** [comment] 2015-08-09 19:43
Most probably video corruption was caused by introduction of hardware-accelerated video decoding. Now it's disabled by default, so there should be no issues with default configuration. As for enabled hwdec, well, I can't fix it anyway.

**Comment by i-rinat** [comment] 2015-08-09 19:44
> `[fresh] [warning] ppb_var_var_to_utf8, 'var' is not a string, (0)`

I've found what causes such messages. It was creating of instance with no movie, just plain `<embed>`. Some websites use such trick to check for installed Flash player.

**Closed by i-rinat** 2015-08-09 19:44 UTC
