### ISSUE TITLE
Firefox 40 freeze

### ISSUE THREAD

**Issue by texstar** [i-rinat/freshplayerplugin#251] opened 2015-08-11 23:38 UTC
Firefox 40 seems to freeze on some websites when scrolling (yahoo.com) with the freshplayerplugin installed. Firefox 39.0.3 works fine.

**Comment by texstar** [comment] 2015-08-12 03:56
Please disregard. It is apparently isolated to yahoo and who knows about them.

**Comment by conraid** [comment] 2015-08-12 14:19
No, not only Yahoo. Also other sites give me the same problem. Especially in video. If FF 39.* crashes only plugin, with FF 40 to freeze and I have to kill firefox.

**Comment by i-rinat** [comment] 2015-08-12 21:50
Confirmed here. Looks like Firefox doesn't like when I call Javascript from `NPP_SetWindow`. I'll look into how to do it asynchronously.

**Comment by rdiaspaulucci** [comment] 2015-08-14 18:07
Freshplayer crashes with firefox 40. Player plugin is not load. Always the Firefox show me to reload the page but without sucess. Every page with flash has the same problem.

**Comment by rdiaspaulucci** [comment] 2015-08-14 18:10
By the way, your freshplayer it always helped me with my works.

**Comment by i-rinat** [comment] 2015-08-14 19:39
OK, I finally tried to postpone Javascript call, to call asynchronously, from a callback with help of `NPN_PluginThreadAsyncCall`, but it still hangs sometimes, waiting for some conditional variable inside NPAPI code in `plugin-container`. 

This all most probably related to new asynchronous initialization of NPAPI plugins landed in Firefox 40. I can't say for sure yet, but looks like it wait for final initialization, which causes deadlock. Perhaps no one expected a plugin calling Javascript code from `NPP_SetWindow`, but it's required by freshwrapper.

**Comment by i-rinat** [comment] 2015-08-14 19:40
Please try to disable asynchronous initialization by setting `dom.ipc.plugins.asyncInit` parameter to `false` on `about:config` page. Looks like it helps to fix hangs on Yahoo.com page on my machine.

**Comment by conraid** [comment] 2015-08-15 08:36
I tried with that change in about: config, but the problem is not solved.
When flash crashes, freezes FF and are forced to kill it. With FF 39.* crashes only containeir and it was enough to reload the page.

I'm sorry for my bad english.

**Comment by i-rinat** [comment] 2015-08-15 20:19
Indeed, I saw couple of times it frozen too, with `asyncInit` disabled. The same deadlock inside `NPN_Invoke`.

The bad part is when I downloaded sources and prepared to make bisection (to find changeset in Firefox code where it was started), freezes gone. :-(

> I'm sorry for my bad english.

I'm not a native speaker too, so I can't tell whenever it's bad or not. As long as we understand each other, it's fine. :smile:

**Comment by i-rinat** [comment] 2015-08-15 21:01
By the way, does https://i-rinat.github.io/flash-test-cases/ContinuousResizing/index.html hang browser?

**Comment by conraid** [comment] 2015-08-17 08:54
No, it works well.
The problem is that I have not found something that I always mistake, just sometimes, mostly video and live streaming in various sites.
But when the problem by plugins, freezing the entire browser, and not just the plugin container.

**Comment by i-rinat** [comment] 2015-08-17 09:12
> freezing the entire browser

Some calls between plugin container process and browser are synchronous, so usual routine is to call and wait for answer. Bad part is that communication is two-way, therefore there is a possibility that both browser and plugin container make a call and both wait. I had similar issue in freshwrapper too for a long time; was the most annoying bug, and the most difficult to solve.

**Comment by cbirchinger** [comment] 2015-09-26 17:47
Is there a way to make issue appear less often? On my Ubuntu machine that has FF 41.0 now and the webupd8 version of the plugin, it never crashes.
On my Gentoo desktop, where i use FF 41.0 and the latest git version for the plugin, i can barely survive 10 minutes without crashing and have to reinstall FF 39.x again, which is probably really unsafe by now.

Also, is this an issue that only hits very few installations? I hardly see anyone reporting this issue anywhere.

**Comment by i-rinat** [comment] 2015-09-26 23:25
> Is there a way to make issue appear less often?

Probably, yes. Most of the time freezes I saw were caused by Javascript call from NPP_SetWindow. I've found a way to avoid that, in a6a11b58f5493415ec063fd0a05512c963218d3a. You could check whenever it helps by compiling version from [dev](https://github.com/i-rinat/freshplayerplugin/tree/dev) branch.

> Also, is this an issue that only hits very few installations? I hardly see anyone reporting this issue anywhere.

It only happens when timings meet certain conditions. Such bugs can happen on one machine and be absent on all others. Attaching debugger often slows program a bit, and could make bug disappear. Or appear where there were no bug. It depends.

One of the classic examples is acquiring two locks in different order. Say, first thread acquires A and then B, while second acquires B and only then A. If any of those threads manage to acquire two locks before other take a chance of capturing any, everything is fine. But if first thread captures A, and at the same time second thread captures B, they then wait indefinitely, because first thread waits for B, which is locked by second thread. And second thread waits for A, but it's locked by first thread.

Here Firefox have two processes, main and plugin container. They can make requests each other, and do them in synchronous way, with active wait for reply. Most of the time they manage to complete quickly, but if both main process and plugin container will ask each other at the same time, both block.

I need to know where plugin rectangle is located in respect to the main window. So when browser changes position, it calls NPP_SetWindow. Browser part wraps parameters of the call into a message and pass it to the plugin-container, which in turn calls NPP_SetWindow function of a plugin. My NPP_SetWindow handler evaluates some Javascript code. To get results, plugin container sends a message to the browser, which evaluates expression, and sends back a message with the results.

That increased message density meet Firefox 40 asynchronous NPAPI initialization changes, and boom! — we have a bug.

At the moment I can only workaround it by moving away from calling Javascript in NPP_SetWindow. But even if that helps, bug in inter-process communication (IPC) is still there.

**Comment by i-rinat** [comment] 2015-09-27 13:07
Merged a6a11b58f5493415ec063fd0a05512c963218d3a into `master` branch. (`dev` was deleted).

**Comment by i-rinat** [comment] 2015-09-29 21:54
Hello? Anybody? Does a6a11b58f5493415ec063fd0a05512c963218d3a help anyhow?

**Comment by cbirchinger** [comment] 2015-09-29 22:29
Not on my main machine. It segfaulted after 4-5 minutes.

dmesg:
Chrome_ChildThr[31692]: segfault at 0 ip 00000000004093fd sp 00007fd167ffe500 error 6 in plugin-container[400000+71000]

output:
[NPAPI 31690] WARNING: pipe error (3): Connection reset by peer: file /var/tmp/portage/www-client/firefox-41.0/work/mozilla-release/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 459
[NPAPI 31690] ###!!! ABORT: Aborting on channel error.: file /var/tmp/portage/www-client/firefox-41.0/work/mozilla-release/ipc/glue/MessageChannel.cpp, line 1753
[NPAPI 31690] ###!!! ABORT: Aborting on channel error.: file /var/tmp/portage/www-client/firefox-41.0/work/mozilla-release/ipc/glue/MessageChannel.cpp, line 1753

**Comment by cbirchinger** [comment] 2015-09-29 23:17
"enable_windowed_mode = 0" seems a tiny bit more stable .. i "only" had 2 freezes within an hour and in both cases i could "killall plugin-container" and recover from it without Firefox fully crashing.

**Comment by i-rinat** [comment] 2015-09-30 15:01
I was hoping that will fix it.

But anyway, on which site it freezes most often? How should I use it to make it freeze sooner? (Scrolling Yahoo title page doesn't freeze on my machine anymore.)

> error 6 in plugin-container

Looks like some other error. 6 is an SIGABRT, which is raised by assertions in the code. Could you collect core file and get a backtrace from it? I'd like to know which assertion fails. Does it happen often enough? It would be nice to know where and how can I reproduce it on my machine.

**Comment by conraid** [comment] 2015-09-30 16:40
Mh
With "enable_windowed_mode = 0" I also have a different result than before.
I have the same freeze, but at least crash only plugin and not FF. 
However, at some sites, like streaming sports, often crashes

**Comment by cbirchinger** [comment] 2015-09-30 16:52
I was mostly using the Twitch video player and opening and closing different streams and hoping that this would trigger it faster. But the crash sometimes happens after i did anything and just opened a different tab without any flash content. So i don't have a perfect way to always trigger it.

This box just has a bit more complex setup than others. I'm using multi-head etc.

So for analysing core dumps. I enabled them will check if it at least starts creating them. However, Firefox (and 2-3 other monsters like Libreoffice) are not built with debug symbols, as this exceeds the poor tmpfs/memory resources on this machine. The plugin itself would have debug symbols though.

**Comment by i-rinat** [comment] 2015-09-30 19:09
> Firefox (and 2-3 other monsters like Libreoffice) are not built with debug symbols

Having debug information from freshplayerplugin should be enough, especially if crash is somewhere inside.

**Comment by cbirchinger** [comment] 2015-09-30 21:40
I could trigger a crash with a core dumb 2 times. However the gdb backtrace looks really worth less.

Because of:
Core was generated by `/usr/lib64/firefox/plugin-container /usr/lib64/nsbrowser/plugins/libfreshwrappe'.
I'm running:
~$ gdb /usr/lib64/firefox/plugin-container core
I still get the warning:
warning: core file may not match specified executable file.

I did not replace or rebuild any binaries between the run and the trace, so i don't know if
that warning means anything or it's just a default comment.

I cannot attach the "thread apply all bt" TXT file i did, i'm getting this every time:
"Something went really wrong, and we can’t process that file.  Try again."

Can i send the TXT (30220 bytes) somewhere? 

The smaller "bt full" shows a thread that doesn't seem to have much info regarding this issue.

**Comment by cbirchinger** [comment] 2015-09-30 21:48
I had to send the .txt output by email. Github is rejecting every .txt attachment from me with:

   Something went really wrong, and we can’t process that file.

**Comment by i-rinat** [comment] 2015-09-30 22:18
I've got both files. There is no sensitive information, so I think it's fine to put `bt-full.txt` here:

```
[New LWP 12338]
[New LWP 12339]
[New LWP 12340]
[New LWP 12341]
[New LWP 12361]
[New LWP 12357]
[New LWP 12362]
[New LWP 12372]
[New LWP 12364]
[New LWP 12365]
[New LWP 12369]
[New LWP 12387]
[New LWP 12498]
[New LWP 12370]
[New LWP 12500]
[New LWP 12358]
[New LWP 12501]
[New LWP 12363]
[New LWP 12499]
[New LWP 12360]
[New LWP 12359]
[New LWP 12336]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `/usr/lib64/firefox/plugin-container /usr/lib64/nsbrowser/plugins/libfreshwrappe'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00000000004093fd in mozalloc_abort(char const*) ()
#0  0x00000000004093fd in mozalloc_abort(char const*) ()
No symbol table info available.
#1  0x00007f29f5807620 in NS_DebugBreak () from /usr/lib64/firefox/libxul.so
No symbol table info available.
#2  0x00007f29f5ae01c0 in ?? () from /usr/lib64/firefox/libxul.so
No symbol table info available.
#3  0x00007f29f5ae0260 in ?? () from /usr/lib64/firefox/libxul.so
No symbol table info available.
#4  0x00007f29f0102c38 in event_persist_closure (ev=<optimized out>, base=0x7f29e6e97000) at /var/tmp/portage/dev-libs/libevent-2.0.22/work/libevent-2.0.22-stable/event.c:1319
        evcb_fd = 3
        evcb_callback = 0x7f29f5aabcf0
        evcb_res = <optimized out>
        evcb_arg = 0x7f29e6e9f000
#5  event_process_active_single_queue (activeq=0x7f29e6e1a680, base=0x7f29e6e97000) at /var/tmp/portage/dev-libs/libevent-2.0.22/work/libevent-2.0.22-stable/event.c:1363
        ev = <optimized out>
        count = 1
#6  event_process_active (base=<optimized out>) at /var/tmp/portage/dev-libs/libevent-2.0.22/work/libevent-2.0.22-stable/event.c:1438
        activeq = 0x7f29e6e1a680
        i = 0
        c = 0
#7  event_base_loop (base=0x7f29e6e97000, flags=1) at /var/tmp/portage/dev-libs/libevent-2.0.22/work/libevent-2.0.22-stable/event.c:1639
        evsel = 0x7f29f0335be0 <epollops>
        tv = {tv_sec = 139817943820816, tv_usec = 139817943821072}
        tv_p = <optimized out>
        res = <optimized out>
        done = 0
        retval = 0
        __func__ = "event_base_loop"
#8  0x00007f29f5aabbd8 in ?? () from /usr/lib64/firefox/libxul.so
No symbol table info available.
#9  0x00007f29f5ab19ad in ?? () from /usr/lib64/firefox/libxul.so
No symbol table info available.
#10 0x00007f29f5ac087f in ?? () from /usr/lib64/firefox/libxul.so
No symbol table info available.
#11 0x00007f29f5aba9aa in ?? () from /usr/lib64/firefox/libxul.so
No symbol table info available.
#12 0x00007f29f9c62224 in start_thread () from /lib64/libpthread.so.0
No symbol table info available.
#13 0x00007f29f3cf75ed in clone () from /lib64/libc.so.6
No symbol table info available.
```

As far as I can tell, debug assertion fails in receiver code in `plugin-container`. There are two possible explanations: (1) logic error in plugin-container code itself, or (2) freshplayerplugin code corrupts memory, and assertion fails because of that.

**Comment by cbirchinger** [comment] 2015-09-30 23:16
To give it bit more context. I've only switched between Firefox 39 and 41. I didn't update or even rebuild any other component of this machine besides Firefox and the plugin for the testing.

I've switched to freshplayerplugin in november 2014. The desktop has been running mostly 24/7 for the past 2 years and Firefox sometimes ran for weeks until i updated to version 40.

**Comment by madovsky** [comment] 2016-02-11 23:50
I just tested firefox 44 with last freshwrapper git and works like a charm

**Comment by i-rinat** [comment] 2016-05-14 23:10
I'm closing this bug. Firefox is already at 46.0.1, and haven't seen any freezing for a long time now. If there would be new information, feel free to open a new issue, or reopen this one.

**Closed by i-rinat** 2016-05-14 23:10 UTC
