### ISSUE TITLE
flashing videos in full screen mode on dailymotion

### ISSUE THREAD

**Issue by daddy33** [i-rinat/freshplayerplugin#267] opened 2015-09-09 10:58 UTC
Hello,

I noticed that videos are flashing a lot when in full screen on dailymotion. I have tried different parameters in freshwrapper.conf but it didn't help.

Thanks.

**Comment by i-rinat** [comment] 2015-09-13 19:54
Hi. I can't reproduce it, videos on dailymotion.com play fine both on page, and in full screen.

Does it happen only on dailymotion, or other sites are also affected? Was it always that way, or did it start after some freshplayerplugin version? If yes, could you find breaking change by using `git bisect`?

Also try to configure with `cmake -DWITH_GLES2=0 -DCMAKE_BUILD_TYPE=Debug ..` and compile. Configured that way, freshwrapper will use GLES2 emulation on top of OpenGL. Perhaps there are some issues with GLES2.

**Comment by daddy33** [comment] 2015-09-13 20:11
Hi. I can reproduce this every time, on three different computers with three different distros (Mint 17.2 Cinnamon 64 bits and 32 bits, and Archlinux 64 bits with Plasma 5 DE). I can't remember when it started, in fact I watched a video on dailymotion for the first time with freshplayerplugin not so long ago.
Thanks a lot for your suggestion, I will try it right now and give you feedback as soon as possible.

**Comment by daddy33** [comment] 2015-09-14 21:48
I configured the plugin as you suggested, but there is no change. I have also tried to use Nvidia proprietary drivers, but still the same problem. Same problem in midori just like in firefox.
Note that I don't have this issue if I use google-chrome. Does not seem to be a problem of window manager as I wrote above. 
In fact when I first installed Nvidia proprietary drivers, the nvidia module was not loading on start, resulting in a Cinnamon crash and going back to fallback mode. In this particular case, strangely, there was no flashing.

**Comment by azuwis** [comment] 2015-09-15 13:45
I can reproduce it on Intel HD 5000 using default configure (no -DWITH_GLES2=0).

Here is the bisect log:

git bisect start 'v0.3.2' 'v0.3.1'
git bisect bad a94a1c6218c0e7fa1b971cdec1ea76c7df911b1e
git bisect good 68844111f8a4ef81bfecfc16b055c38af29f770d
git bisect bad 20359c0f044ca071d5069c7dd20785025706e981
git bisect bad 491b5b47c742b56105a18519420f0ed58bf36ac9
git bisect good 87f8488bfd9e9c7abf6c0923bb96dcb012d138fc
491b5b47c742b56105a18519420f0ed58bf36ac9 is the first bad commit

**Comment by i-rinat** [comment] 2015-09-19 22:29
Managed to reproduce under Cinnamon with software rendering. Occasionally, screen goes black. Then, on next frame picture is restored. Looks like it turning off vsync (`enable_vsync = 0`) turns off that blackouts too.

For some unknown reason, those blackouts are caused by delaying GraphicsExpose events in delay thread.

**Comment by m00ster** [comment] 2015-09-25 04:25
I am also seeing this behavior on daily motion, oddly enough .. it is the only site i am seeing the errors with.

**Comment by m00ster** [comment] 2015-09-25 04:34
I still get the flashing under cinnamon with hardware rendering using latest nvidia drivers 355.11. I tried setting vsync to 0 like so:

# microseconds to wait after vsync event
vsync_afterwait_us = 0

# fullscreen transition delay, in milliseconds
fs_delay_ms = 300

# wait for vertical blank event before drawing on screen
enable_vsync = 0

but still get flashing.

I have 3d enabled as well as vdpau. It works great on other sites.

**Comment by i-rinat** [comment] 2015-11-21 22:58
Even if I was able to reproduce the bug, there were no obvious X11 error reports. X Window related code always as an X server for so-called backing store. It's like double buffering — a pixmap which stores all window content. So when X server want to draw a window it can use that pixmap rather than waiting for application to provide a picture. That technique requires more RAM, but helps to avoid flicker.

I don't know, maybe compositing manager in Cinnamon doesn't respect those settings? Anyway, further debugging requires to dig into that compositing manager code, which I'm not proficient at.

**Comment by i-rinat** [comment] 2016-05-14 23:03
There was similar issue #323 recently. I believe that both this and that issue were caused by lack of synchronization between GL hardware and X server pixmaps. With additional synchronization issue should be fixed.

**Closed** 2016-10-04 22:49 UTC
Labels: fixed
