### ISSUE TITLE
again video problem with https everywhere ?

### ISSUE THREAD

**Issue by promeneur** [i-rinat/freshplayerplugin#316] opened 2016-03-14 13:06 UTC
Opensuse 13.1 x86_64
FF 45.0
Freshplayerplugin 0.3.4-19.5
https everywhere 5.1.4

http://www.lemonde.fr/videos/video/2016/03/14/comprendre-la-mission-exomars-en-3-minutes_4882300_1669088.html

again problem with https everywhere as in the past (issue 174) ?

strangely i get only sound and no picture

if i inactivate https everywhere then  i get sound and picture .

**Comment by promeneur** [comment] 2016-03-14 13:14
more info : 
after 40 s i get picture
if i inactivate httpseverywhere i get picture immediately.

**Comment by i-rinat** [comment] 2016-03-15 22:40
I can't reproduce it with HTTPS Everywhere enabled, so can't say for sure. But if it was directly related, there would be no sound at all. And there would be no appearing picture after certain timeout. Previous issue (#174) was about blocking file loading completely. Here is something else, more subtle.

**Comment by madovsky** [comment] 2016-03-15 22:47
promeneur: try to disable SELINUX,
everything works for me with FF 48

**Comment by promeneur** [comment] 2016-03-16 05:37
i use opensuse 13.1 . what is selinux ?

**Comment by madovsky** [comment] 2016-03-16 11:40
SELINUX is like a system security daemon check everything abnormal in your system.
open /etc/sysconfig/selinux, modify the SELINUX=... with SELINUX=disabled
reboot and test freshwrapper again. If it's the same so put your selinux back and reboot again

**Comment by i-rinat** [comment] 2016-03-16 12:10
SELinux is an access control system. It either permits access or blocks it. It can't block something for 40 seconds, and then allow it. Moreover, if there is a sound, then swf movie was loaded. Bug is somewhere in the display pipeline.

**Comment by promeneur** [comment] 2016-03-16 12:11
there is no selinux with opensuse but apparmor . 
apparmor is disable by default with 13.1.

**Comment by madovsky** [comment] 2016-03-16 12:17
ok my mistake.

**Comment by promeneur** [comment] 2016-03-27 09:16
hello pb disappeared !
i forget to say that my graphic adapter is an intel one

recently i installed libvdpau-va-gl and i update all about x11/xorg from
http://download.opensuse.org/repositories/X11:/XOrg/openSUSE_13.1/

but there is a pb when displaying video at www.lemonde.fr : 
many pixels displayed (not during commercial)

no pb with some other site i know well.

**Comment by madovsky** [comment] 2016-03-27 09:31
my suggestion is to not go to lemonde.fr :)

**Comment by i-rinat** [comment] 2016-05-14 22:39
> many pixels displayed (not during commercial)

There are many types of visual glitches. And seeing one can tell much more that a textual description. (A screenshot would be great).

But from that sentence I can guess that there is something related to video decode acceleration. I did some testing and see that player on lemonde.fr uses hardware acceleration. I can't easily force site to show me video commercial, but I guess it's played without hw acceleration [1]. Hence the difference.

In 0.3.4 there was a bug which affected hw video decoding on some sites. Data blocks were passed to decoder in a wrong order, which caused glitches. That bug was fixed in v0.3.5 release. Could you try recent version and check if visual distortions are still present?

[1] Commercials on Youtube are played without hw decoding, even if it's used for main video playback.

**Comment by promeneur** [comment] 2016-05-23 07:30
freshplayerplugin 0.3.5
Flashplayer 21.00.242

no more pb

thanks

**Closed** 2016-05-23 09:14 UTC
