### ISSUE TITLE
freshplayerplugin will not install on Linux Mint 18 again

### ISSUE THREAD

**Issue by DWSampson** [i-rinat/freshplayerplugin#348] opened 2016-10-22 13:48 UTC
Hi Rinat

It seems a new issue has now cropped up, it would appear that Clement Lefebvre and his team who develop and maintain Linux Mint 18 onwards, have made some minor, but very discreet changes to the o/s.

As the freshplayerplugin will now not install, it seems the o/s is blocking this somehow. I had to re-install Linux mint as I have change desktop tower PC's. 

I have uploaded the screen shot for your perusal, the portion you need to look at is this "prerm called with unknown argument `install'"

I have not encountered this error before, as I had linux mint 18 on the previous machine, so what the problem is, isn't clear.
Kind Regards

Derrick W. Sampson

United Kingdom

![screenshot from 2016-10-22 14-18-00](https://cloud.githubusercontent.com/assets/22998533/19619770/456529d6-9866-11e6-930a-3afcd41b4815.png)

**Comment by i-rinat** [comment] 2016-10-22 20:13
Hi.

This error is most probably is in the binary package. As you may know, Debian packages (Mint and Ubuntu both use Debian package format) have also supplementary scripts, `preinst`, `postinst`, `prerm`, `postrm`, which are called before or after installation or removal.

[Packaging manual](https://www.debian.org/doc/debian-policy/ch-maintainerscripts.html) says that `prerm` script can be called with actions `remove`, `upgrade`, `remove in-favour`, `deconfigure in-favour`, and `failed-upgrade`. So all scripts are expected to handle all those actions, but are not required to handle others. Most of script do nothing, but also most of them have error checking. As you can see, action `install` for `prerm` script is not mentioned in the allowed action lists. And it has no sense to call pre-removal script with action called `install`, since package is going to be removed.

I think, you're trying to install `browser-plugin-freshplayer-pepperflash_0.3.6-1~webupd8~xenial5_amd64.deb` from WebUpd8 PPA. If so, here is what its `prerm` script looks like:
```
#! /bin/sh

set -e

case "$1" in
    remove|deconfigure)
        update-alternatives --remove \
        mozilla-flashplugin \
        /usr/lib/browser-plugin-freshplayer-pepperflash/libfreshwrapper-flashplayer.so
        ;;

        failed-upgrade)
        ;;

        upgrade)
        ;;

        *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac
```
As you can see, if called with `install` argument, it prints error message and terminates with error code 1, which in turn stops package manager.

The best solution would be to fix package manager in Mint. It shouldn't pass `install` action.

But there is also a workaround that you can use immediately. Edit file `/var/lib/dpkg/info/browser-plugin-freshplayer-pepperflash.prerm`, remove `exit 1` line. That will prevent script from returning error. You then will need to call `dpkg --configure -a` as root to allow package manager to call all required scripts and mark packages as installed in its database.

**Comment by DWSampson** [comment] 2016-10-23 08:49
Hi

I have followed your instruction on the latter first, and it would seem that Linux Mint has fouled the download up, because I typed in, in terminal "cd /var/lib/dpkg/info/" then used "gedit browser-plugin-freshplayer-pepperflash.prem, only to find that, that file does not exist.. The only file that does exist is pepperflash-plugin-nonfree.prem. And on the former we have Synaptic Package Manager, not Package Manager, if it's the Synaptic Package Manger that needs fixing, how to I do this?

**Comment by i-rinat** [comment] 2016-10-23 21:40
Guess what? I was wrong. I installed Mint 18 into virtual machine, added PPA, tried to install `browser-plugin-freshplayer-pepperflash` and got the same error. Then tried to debug dpkg, only to find that it's `preinst` is failing, not `prerm`. Package manager is fine, and it even gave a pointer. It said: "pre-installation script returned error exit status 1". But I was mislead by that "prerm called with unknown argument".

The package have also `preinst` script probably copied from `prerm`:
```
#! /bin/sh

set -e

case "$1" in
    remove|deconfigure)
        ;;

        failed-upgrade)
        ;;

        upgrade)
        update-alternatives --remove \
        flash-mozilla.so \
        /usr/lib/browser-plugin-freshplayer-pepperflash/libfreshwrapper-flashplayer.so
        ;;

        *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac
```

It's fine for `preinst` script to be called with `install` parameter. And if `preinst` from a package doesn't handle it, it's a packaging error.

**Comment by i-rinat** [comment] 2016-10-23 21:43
Hello, @hotice.
There is very suspicious `preinst` script in `browser-plugin-freshplayer-pepperflash_0.3.6-1~webupd8~xenial5_amd64.deb`. Looks like there were some kind of copying from `prerm`, but `install)` case wasn't added. So package can't be installed. Could you take a look, please?

**Comment by i-rinat** [comment] 2016-10-23 21:49
> used "gedit browser-plugin-freshplayer-pepperflash.prem, only to find that, that file does not exist

My knowledge is outdated — `dpkg`'s behaviour have changed, it now unpacks scripts into a temporary directory, which is deleted after. So that trick with editing files and continuing installation won't work anymore.

**Comment by hotice** [comment] 2016-10-24 11:04
I'm working on a fix, thanks for mentioning this!

**Comment by hotice** [comment] 2016-10-24 11:29
Done, the Ubuntu 16.04 / Linux Mint 18 package should be fixed. For other Ubuntu / Mint versions, the packages are still waiting to be built in my test PPA (Launchpad is laggy today). @DWSampson try to install the latest version (so run "sudo apt update" before trying to install it), it should work now.

**Comment by DWSampson** [comment] 2016-10-24 11:53
Thanks for the heads up @hotice will let you know how I get on, have also posted this link on Webupd8, so that other uses of Linux Mint 18 know what's going.

**Comment by DWSampson** [comment] 2016-10-24 12:01
@hotice Sorry no joy!! Please see attached Screen-shot
![screenshot from 2016-10-24 12-57-38](https://cloud.githubusercontent.com/assets/22998533/19644789/9da1451a-99e9-11e6-855c-9357c2e04273.png) , if people wish to play online games they will temporarily need to use Chromium until this is fixed.

**Comment by hotice** [comment] 2016-10-24 12:02
This was a bug on my part, not in Mint. I explained everything in a reply to your comment on [WebUpd8](http://www.webupd8.org/2014/05/install-fresh-player-plugin-in-ubuntu.html#comment-2966162439), which I'll copy/paste here for reference:

_The issue is not with Mint and not even Ubuntu. Google no longer bundles pepper flash with Google Chrome. To get Pepper Flash, you need to install the adobe-flashplugin package, which is available in the Ubuntu Partner repository (which needs to be enabled manually on Ubuntu but I think it's available directly in Linux Mint). The bug report you posted was an issue caused by my packaging, trying get the browser-plugin-freshplayer-pepperflash package to work with these changes.

I fixed the issue now.

So to get Pepper Flash to work in Firefox now, you must install browser-plugin-freshplayer-pepperflash and adobe-flashplayer (this is already in this article, as I've updated it last week)._

**Comment by hotice** [comment] 2016-10-24 12:05
@DWSampson hmm the initial issue was that the package failed to install, not that it wasn't found. The package is in my PPA as you can see here: https://launchpad.net/~nilarimogard/+archive/ubuntu/webupd8/+packages?field.name_filter=freshplayerplugin&field.status_filter=published&field.series_filter=

Can you please try to update the software sources and try again? This should do it:
```
sudo apt update
sudo apt install browser-plugin-freshplayer-pepperflash
```
If it still doesn't work, please post the output of:
```
apt-cache policy browser-plugin-freshplayer-pepperflash
```

**Comment by hotice** [comment] 2016-10-24 12:06
@DWSampson looking closer to your screenshot, you added a dot (".") at the end of the install command. Remove that and it should work.

**Comment by DWSampson** [comment] 2016-10-24 12:15
@hotice will give that a go, give me a few minutes

**Comment by hotice** [comment] 2016-10-24 12:15
@DWSampson  I had a typo in my earlier comment. You must install browser-plugin-freshplayer-pepperflash and adobe-flashplugin (I typed "adobe-flashplayer"). So this should install everything you need to get pepper flash to work in Firefox:
```
sudo apt install browser-plugin-freshplayer-pepperflash adove-flashplugin
```

(As a side note, the browser-plugin-freshplayer-pepperflash package has a "Recommends" field for adobe-flashplugin, which results in adobe-flashplugin being installed automatically in Ubuntu however, Linux Mint does not install recommended packages by default, so it needs to be installed manually).

**Comment by hotice** [comment] 2016-10-24 12:16
@DWSampson  I had a typo in my earlier comment. You must install browser-plugin-freshplayer-pepperflash and adobe-flashplugin (I initially typed "adobe-flashplayer" so in case you're reading that in your email, you won't see the edit). So this should install everything you need to get pepper flash to work in Firefox:
```
sudo apt install browser-plugin-freshplayer-pepperflash adobe-flashplugin
```

(As a side note, the browser-plugin-freshplayer-pepperflash package has a "Recommends" field for adobe-flashplugin, which results in adobe-flashplugin being installed automatically in Ubuntu, however, Linux Mint does not install recommended packages by default, so it needs to be installed manually).

**Comment by DWSampson** [comment] 2016-10-24 12:21
@hotice  it's installed it. please see screen shot.
![screenshot from 2016-10-24 13-20-02](https://cloud.githubusercontent.com/assets/22998533/19645455/b36ca094-99ec-11e6-82d6-618760b53bf2.png)

**Comment by hotice** [comment] 2016-10-24 12:30
@DWSampson great, thanks for the confirmation! Like I said earlier, make sure to also install ```adobe-flashplugin``` to actually get pepper flash working on Firefox.

**Comment by DWSampson** [comment] 2016-10-24 12:34
It's worked issue resolved. @hotice have amended Synaptic Package Manager preferences accordingly to "Consider recommended packages as dependencies, in addition to this I have also set "Repositories to enable source code repositories".

**Closed** 2016-12-22 18:00 UTC
Labels: upstream-issue
