### ISSUE TITLE
Flash player area flickering

### ISSUE THREAD

**Issue by hexchain** [i-rinat/freshplayerplugin#323] opened 2016-04-16 04:18 UTC
First, thanks for this amazing work!

I'm having some problem watching videos on bilibili.com (sorry for the Chinese-only site but I cannot seem to reproduce on any other video sites). [Sample](http://www.bilibili.com/video/av1252354/), click the video area and it'll start playing.

The flash area flickers a lot when playing video (no flickering when paused). Turning off `enable_3d` seems to be a valid workaround, but if I'm right this also turns off all hardware decoding. Turning on or off compositor has no effect. Using intel or modesetting DDX driver does not affect this problem, too.

I don't have this problem with chromium but there's no hardware decoding in Linux Chromium anyway.

I'm using Arch Linux, fully upgraded.
```
firefox 45.0.2-1
chromium 50.0.2661.75-1
chromium-pepper-flash 1:21.0.0.216-1
freshplayerplugin-git v0.3.5.r1.g99c5aa1-1
linux 4.5.1-1
xorg-server 1.18.3-1

VGA compatible controller [0300]: Intel Corporation Skylake Integrated Graphics [8086:1916] (rev 07) (prog-if 00 [VGA controller])
	Kernel driver in use: i915
```

**Comment by i-rinat** [comment] 2016-04-30 23:12
Interestingly enough, now that sample video doesn't work anymore in freshplayerplugin, but still works in Chrome.

**Comment by hexchain** [comment] 2016-05-01 03:29
Well, I have no problem playing that video in both Firefox and Chromium (except for the flickering in freshplayerplugin). Since it's a Chinese site, maybe there's connectivity issue?

**Comment by Aetf** [comment] 2016-05-01 06:13
@hexchain Are you getting flickers even not in fullscreen mode? On my box, it works perfectly if I don't make it fullscreen.

I can play the sample video from US without a problem, and can reproduce the flicker in fullscreen mode. Setting `enable_3d=0` does fix the issue, but it breaks the `device_scale=1.5` in fullscreen mode.

Related version
```
Arch Linux

firefox-nightly 49.0a1.20160501-1
google-chrome 50.0.2661.94-1
freshplayerplugin-git v0.3.5.r1.g99c5aa1-1
xorg-server 1.18.3-1
xf86-video-intel 1:2.99.917+636+g562ae1f-1
linux 4.5.1-1
```
Hardware
```
00:02.0 VGA compatible controller: Intel Corporation Broadwell-U Integrated Graphics (rev 09)
```

**Comment by hexchain** [comment] 2016-05-01 06:18
@Aetf yes, even not in fullscreen mode.

Plus, I don't have the Xorg DDX driver `xf86-video-intel` installed according to a note on [this page](https://wiki.archlinux.org/index.php/Intel_graphics), but it does not seem to affect this issue.

**Comment by i-rinat** [comment] 2016-05-01 11:20
> Since it's a Chinese site, maybe there's connectivity issue?

It works fine in Chrome, so most probably that's just another bug in freshplayerplugin.

**Comment by i-rinat** [comment] 2016-05-01 11:31
Firefox just blocked http://87.245.198.80/ because "web page at 87.245.198.79 has been reported to contain unwanted software". At least, video's now working.

**Comment by i-rinat** [comment] 2016-05-01 13:46
Could you try code from [use-tripple-buffering](https://github.com/i-rinat/freshplayerplugin/compare/use-tripple-buffering) branch? I've made GL context there double-buffered.

Also, what flickering looks like? Is it white flashes or black? How often, several times a second, or once in several seconds?

**Comment by hexchain** [comment] 2016-05-01 14:05
It's white flash, sometimes once in several seconds then several times a second, seems completely random.

With code in that branch and `enable_3d=1`, the flash player area is completely black, but I can still interact with the video player and hear sound.

I got these 2 lines in terminal both with code from master and use-tripple-buffering, don't know if relevant:
```
[fresh 30173] not implemented: PPB_OpenGLES2VertexArrayObject;1.0
[fresh 30173] not implemented: PPB_OpenGLES2DrawBuffers(Dev);1.0
```

**Comment by i-rinat** [comment] 2016-05-01 14:55
> the flash player area is completely black, but I can still interact with the video player and hear sound.

@hexchain, what is an output of `glxinfo` command on your machine?

> I got these 2 lines

PepperFlash asks for those interfaces every time. But since they are not required, I didn't implement them. Their absence won't interfere rendering anyhow.

**Comment by i-rinat** [comment] 2016-05-01 14:57
> Setting enable_3d=0 does fix the issue, but it breaks the device_scale=1.5 in fullscreen mode.

@Aetf, there is a size mismatch in full screen mode indeed. Commit f78f909333c76246db84934f5b69a331ab3c0e03 should fix that.

**Comment by hexchain** [comment] 2016-05-01 15:09
Output of `glxinfo` pasted at http://ix.io/yWw

**Comment by i-rinat** [comment] 2016-05-01 16:39
> Output of glxinfo

GLXFBConfigs looks exactly the same as on my machine. So, no luck there.

Could you also try again with `enable_xrender = 0` in config file? That will disable using of XRender. Maybe it fails somehow.

**Comment by Aetf** [comment] 2016-05-01 19:56
@hexchain :
The modesetting  driver looks interesting, and might be the reason why I only get flicker in fullscreen. But I agree that the driver doesn't look like the root cause for this issue.

@i-rinat :
> there is a size mismatch in full screen mode indeed. Commit f78f909 should fix that.

Yes that works. Nice job!

> what flickering looks like?

I got the exactly same flicker as hexchain , but only in fullscreen.

> Could you try code from use-tripple-buffering branch? I've made GL context there double-buffered.

The player area is black, mouse interaction and sound works fine.

> Could you also try again with `enable_xrender = 0` in config file?

No use. The same black.

And [here](https://gist.github.com/Aetf/14fb82178cc12c7ccc4c7ea1e0874973) is my glxinfo output, which looks mostly the same as hexchain's

**Comment by i-rinat** [comment] 2016-05-01 20:01
Found another player that is not fixed with f78f909333c76246db84934f5b69a331ab3c0e03, so 8c5967cb99fc430df4ece1a39f55e0934f1cd2a9 was added.

**Comment by i-rinat** [comment] 2016-05-01 21:17
Oh, I've just realized why double-buffering code makes no picture. (And why there were no double buffering before in the code). GLX allows to create double-buffered GLX Pixmap, but `glXSwapBuffers()` is silently ignored for such pixmaps.

**Comment by i-rinat** [comment] 2016-05-01 22:11
OK, next attempt, now in [use-second-pixmap-g3d](https://github.com/i-rinat/freshplayerplugin/compare/use-second-pixmap-g3d) branch. Now there are two sets of Pixmap and Pictures. One of them is used as a buffer.

Has it any effect on flickering?

**Comment by Aetf** [comment] 2016-05-02 01:46
That's working! I can't reproduce the flicker any more. Let's see if the patch also works for @hexchain .

**Comment by hexchain** [comment] 2016-05-02 03:12
With the use-second-pixmap-g3d code:

I still have that flickering, but much less this time, only once in several seconds.

Also with `enable_xrender = 0`, the right half of flash player area is black:
![1462158362](https://cloud.githubusercontent.com/assets/529520/14946526/e85162de-1055-11e6-9d23-1c87e03a6766.png)
^ This does not happen with master branch.

**Comment by i-rinat** [comment] 2016-05-02 10:48
> right half of flash player area is black

Forgot to remove width division by 2 which was added during debugging. I've pushed fixed version into the master branch as 4732f473f9c71153c59ce9c4835253470b6e9089.

> I still have that flickering, but much less this time, only once in several seconds.

I think, I saw it too. But can't reproduce now.

And have no idea why it happens. Before, there was a possibility that drawing thread could erase drawing area before browser thread had a chance to put it onto a screen. Now, with explicit copying, that possibility's eliminated.

**Comment by i-rinat** [comment] 2016-05-02 14:13
I tried to save all frames into files, and there are indeed a number of all-white frames. So they are coming from PepperFlash itself. There also no noticable differences in PPB_Graphics3D and PPB_OpenGLES2 calls between normal frames and all-white frames.

**Comment by i-rinat** [comment] 2016-05-02 17:25
Added more synchronizations in afb5209b15a65e4e2e671518c81b14ef254c1144.

It could be that even if `glFinish()` is called and drawing is finished, it takes some time to propagate from GL buffers to X drawables. Adding more synchronization should prevent data race situations, when data is read before it was written. And in my tests it does help.

**Comment by hexchain** [comment] 2016-05-03 04:52
Great! Now I don't see any flickering.

**Comment by i-rinat** [comment] 2016-05-03 12:38
Good. Let's hope that helps indeed.

**Closed** 2016-05-14 17:59 UTC
Labels: fixed
