### ISSUE TITLE
build freshplayerplugin version 0.3.1 no working 0.3.0 100% working

### ISSUE THREAD

**Issue by andykimpe** [i-rinat/freshplayerplugin#235] opened 2015-07-15 18:19 UTC
build freshplayerplugin version 0.3.0 100% working

build freshplayerplugin version 0.3.1 no working

error http://pastebin.com/RjQ8u3Va

is it possible to know that it is exactly the minimum version of pre-requisites

**Comment by MALLER-LAGOON** [comment] 2015-07-15 19:14
just erase your build/ directory and do try it again.

or better yet; try with [this](https://github.com/MALLER-LAGOON/Freshplayer-installer)

**Comment by i-rinat** [comment] 2015-07-15 19:28
Here is false negative in checking for `struct AVVDPAUContext` presence. So the check should be fixed (just recompiling from scratch won't work).

Where can I get ffmpeg package you are using? Binary version should suffice, I need headers only.

**Comment by andykimpe** [comment] 2015-07-15 19:54
Here rpm with the rpm source src.rpm http://demo.ovh.eu/download/336bfc56a90cd6f5fd16db4945ce2e99/ffmpeg-rpm.tar

you would need to install rpm and cpio order to extract these packages can be installed on any Linux distribution

Then simply use file-roller to extract

note I do not think it comes from ffmpeg because some other distributions so the compillation is exactly the same I do not have this problem

**Comment by i-rinat** [comment] 2015-07-15 21:36
Hmm, that looks odd. The structure `AVVDPAUContext` is where it supposed to be, I remember for sure custom include directories was added to scripts, but it still fails for some reason.

**Comment by i-rinat** [comment] 2015-07-15 21:38
In the directory where you build, what `grep HWDEC_INCLUDE CMakeCache.txt` prints?

**Comment by andykimpe** [comment] 2015-07-16 09:43
Here are the CMakeCache.txt http://pastebin.com/fGnJxmV3

**Comment by i-rinat** [comment] 2015-07-17 22:27
Hmm, CMakeCache.txt contents looks fine, and that's odd. I even tried to emulate that with moving libavcodec includes away with simultaneous change of corresponding `.pc` files, but can't reproduce the issue.

So, just to be sure. You are configuring in a clean directory, right?

**Comment by i-rinat** [comment] 2015-07-17 22:29
Try to add line
```
message(STATUS "REQ_INCLUDE_DIRS=${REQ_INCLUDE_DIRS}")
```
after line
```
set(CMAKE_REQUIRED_INCLUDES  "${REQ_INCLUDE_DIRS}")
```
in `cmake/ffmpeg-compat/CMakeLists.txt` file in repository, and then run `cmake ..` from build directory. That will print REQ_INCLUDE_DIRS list contents. Is there path `/usr/include/ffmpeg` in that list?

**Comment by andykimpe** [comment] 2015-07-18 08:32
I'll try this is I want and I'll keep you informed

**Comment by andykimpe** [comment] 2015-07-18 09:08
ok Here it seems to me to return the proper scl seems to be to use library

REQ_INCLUDE_DIRS=/opt/rh/freshplayerpluginscl/root/usr/include/glib-2.0;/opt/rh/freshplayerpluginscl/root/usr/lib64/glib-2.0/include;/opt/rh/freshplayerpluginscl/root/usr/include;/usr/include/alsa;/usr/include/libdrm;/usr/include/cairo;/usr/include/pixman-1;/usr/include/freetype2;/usr/include/libpng12;/usr/include/pango-1.0;/opt/rh/freshplayerpluginscl/root/usr/include/glib-2.0;/opt/rh/freshplayerpluginscl/root/usr/lib64/glib-2.0/include;/usr/include/gtk-2.0;/usr/lib64/gtk-2.0/include;/usr/include/atk-1.0;/usr/include/cairo;/usr/include/gdk-pixbuf-2.0;/usr/include/pango-1.0;/usr/include/pixman-1;/usr/include/freetype2;/usr/include/libpng12;;/opt/rh/freshplayerpluginscl/root/usr/include;/opt/rh/freshplayerpluginscl/root/usr/include;/usr/include/ffmpeg

the level of system dependency that are used I

libdrm 2.4.52

alsa-lib 1.0.22

cairo 1.8.8

pixman 0.32.4

libpng 1.2.49

pango 1.28.1

gtk2 2.24.23

atk 1.30.0

gdk-pixbuf (gdk-pixbuf-devel) package not available while it seems strange be installed

freetype 2.3.11

may be it's library would need to feel more Version I will try to date meter to see

**Comment by Talv** [comment] 2015-07-31 01:24
I was getting exactly the same error. Checked includes and there was nothing wrong with them - it might be missleading.
In my case CMake was simply failing to compile its tests because of broken link to libGL :|
So for future reference: firstly check CMakeError.log for errors during compilation of the tests.

**Comment by i-rinat** [comment] 2015-08-01 11:46
> failing to compile its tests because of broken link to libGL

That could be the case, I link all libraries at once to every test binary, not only libavcodec.

**Comment by i-rinat** [comment] 2015-08-15 12:57
Hello? @andykimpe, does your `CMakeFiles/CMakeOutput.log` contain anything about linking errors?

**Comment by i-rinat** [comment] 2015-08-20 15:35
Added a664a68e697abe0367e694c740a34a34b17d4948, which should improve error message in case of some libraries not available for linking.

**Comment by i-rinat** [comment] 2015-11-02 14:31
I believe the bug described had arised due to a missing `libGL.so`. There is now `link_check` target, added in a664a68e697abe0367e694c740a34a34b17d4948, which will prevent compilation if any of libraries are not linkable.

**Closed by i-rinat** 2015-11-02 14:31 UTC
