### ISSUE TITLE
Full-screen broken for videos with resolution lower than 1080p on youtube

### ISSUE THREAD

**Issue by Ziemas** [i-rinat/freshplayerplugin#178] opened 2015-04-30 18:53 UTC
Bisected to commit 2cda8cc

When full-screening a video with a resolution lower than 1080p it becomes distorted to a small bar at the top off the screen.

Edit:
This does not happen with enable_3d on, but I have another bug to file for that.

**Comment by i-rinat** [comment] 2015-05-01 10:55
I don't have nVidia adapter to test with (and it's hard to put other video adapter to a notebook computer), so can only guess. That commit you are bisected bug to, looks very strange. It's only about setting hints for window manager. Those hints should have no effect on rendering at all. Or at least be consistent: appear in both 2d and 3d modes.

In recent commits 2cd794ee1ef11740c6afa7c39bfdbdf0b45c6fdc and a9b8530960e67d75119fafb4177a425898e0b0d1 I've added request for backing store for windows created. Although they are not directly targeted to fix the bug, they're still related. Could you check if bug still appears in recent version?

**Comment by Ziemas** [comment] 2015-05-01 11:34
Those commits did not fix the problem.

I've double checked 2cda8cc by reverting it on top of master, and confirmed that it introduced the issue.

Maybe it's a window manager thing? I'm using Awesome.

**Comment by i-rinat** [comment] 2015-05-01 12:39
> Maybe it's a window manager thing?

Yes, it's definitely related to window manager. But I don't know how to fix it. Removing those lines will break fullscreen in Gnome 3.

**Comment by i-rinat** [comment] 2015-05-01 15:43
Could you check code from [dev](https://github.com/i-rinat/freshplayerplugin/tree/dev) branch? I changed atom order in 449516d337f3685cdfdac83ce16fc0333319ef3f, maybe that would help.

**Comment by Ziemas** [comment] 2015-05-01 15:51
That fixes the distortion. But now it's just a maximized window, not really full-screen, meaning I still see the taskbar.

**Comment by thierryOrdissimo** [comment] 2015-05-04 07:03
It resembles hard has my probleme. The only means to acquire the full-ecran is to comment in the ticket #176

**Comment by Ziemas** [comment] 2015-05-04 10:53
@thierryOrdissimo 
That seems to be a different issue, commenting that out makes no difference for me.

**Comment by i-rinat** [comment] 2015-05-04 14:22
I've managed to reproduce issue.
Patch 1033647de12ad3f37f4856e0ae0682e811b188c0 should fix it (merged to `master` already).

**Comment by i-rinat** [comment] 2015-05-04 20:09
What about 8ae0a228b07390ed8aebdc1fbae059e128778b26?

**Comment by Ziemas** [comment] 2015-05-04 20:30
Yes, That solves the issue.

**Comment by i-rinat** [comment] 2015-05-05 11:44
OK, great.

**Comment by i-rinat** [comment] 2015-05-07 22:17
@Ziemas, It turns out, some window managers generate multiple Expose events, so previous fixes wasn't completely correct. I've changed fullscreen geometry handling again in 4283d3a461414828583ae4f7dc09c524b63e8079 to address issue arising in Enlightment. Could you check if it still works fine in your setup with Awesome WM?

**Comment by Ziemas** [comment] 2015-05-07 23:42
Yes, it still works fine.

**Comment by i-rinat** [comment] 2015-05-08 08:36
OK, that's good.

**Closed** 2015-05-08 15:49 UTC
Labels: fixed
